language: csharp
mono: none
dotnet: 1.0.3
dist: trusty
solution: ./src/Disqus.Core/Disqus.Core.sln
install:
    - nuget restore ./src/Disqus.Core/Disqus.Core.sln
    - nuget install NUnit.Console -Version 3.6.1 -OutputDirectory testrunner
script:
    - dotnet restore
    - xbuild /p:Configuration=Release ./src/Disqus.Core/Disqus.Core.sln
    - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./src/Disqus.Core/Disqus.Core.Tests/bin/Release/Disqus.Core.Tests.dll
