language: csharp
mono: none
dotnet: 1.0.3
dist: trusty
solution: ./src/Disqus.Core/Disqus.Core.sln
before_install:
    - sudo apt-get install nunit-console
script:
    - dotnet restore
    - xbuild /p:Configuration=Release ./src/Disqus.Core/Disqus.Core.sln
    - nunit-console ./src/Disqus.Core/Disqus.Core.Tests/bin/Release/Disqus.Core.Tests.dll
